export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "REGISTER_REQUEST";
export const LOGIN_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAILURE = "REGISTER_FAILURE";

export const GET_USER_REQUEST = "REGISTER_REQUEST";
export const GET_USER_SUCCESS = "REGISTER_SUCCESS";
export const GET_USER_FAILURE = "REGISTER_FAILURE";

export const LOGOUT = "LOGOUT";
