export const mainCarouselData = [
    {
        image:"https://ideacdn.net/idea/ef/14/myassets/slider_pictures/pictures_2_2.jpg?revision=1703163525",
        path:"/baby/clothing/baby_set"
    },
    {
        image:"https://ideacdn.net/idea/ef/14/myassets/slider_pictures/pictures_2_4.png?revision=1703163525",
        path:"/baby/clothing/baby_set"
    },
    {
        image:"https://ideacdn.net/idea/ef/14/myassets/slider_pictures/pictures_2_1.jpg?revision=1703163525",
        path:"/baby/clothing/baby_set"
    },
    {
        image:"https://ideacdn.net/idea/ef/14/myassets/slider_pictures/pictures_1_2.jpg?revision=1703163302",
        path:"/baby/clothing/baby_set"
    },
    {
        image:"https://ideacdn.net/idea/ef/14/myassets/slider_pictures/pictures_2_3.jpg?revision=1703163525",
        path:"/baby/clothing/baby_set"
    },
    {
        image:"https://ideacdn.net/idea/ef/14/myassets/slider_pictures/pictures_1_6.jpg?revision=1703163302",
        path:"/baby/clothing/baby_set"
    },
]
